apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend      
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: php      
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:                
        - name: www-data
          persistentVolumeClaim:
            claimName: www-pvc
      containers:
      - name: php        
        image: isunyoo/php:7.2-fpm-mysql
        #env:
        #  - name: PHP_INI_SCAN_DIR
        #    value: :/usr/local/etc/php/conf.d
        ports:
        - containerPort: 9000                
        volumeMounts:
          - name: www-data
            mountPath: /var/www/html           
      initContainers:        
        - name: install
          image: busybox          
          volumeMounts:
          - name: www-data
            mountPath: /var/www/html
          command: ["/bin/sh", "-c", "echo '<?php phpinfo(); ?>' > /var/www/html/php_info.php"]                      